[#10] 전역 모달 컴포넌트 구현 및 추상화 리팩토링
f-lab-edu/debus pull request #11
Opened 2024-02-28 07:43 UTC by k-jeonghee

## PR 타입
- [X] 기능 개발

## 작업 내용
### Type 전달형 모달에서 Element를 바로 전달할 수 있도록 단계별 컴포넌트 추상화 

1. modal atom 생성 및 useModal 훅 작성
2. Modal 컴포넌트
3. Overlay 컴포넌트
   - 투명도가 적용된 background
   - 배경 클릭 시 닫힘
5. ModalContainer 컴포넌트
   - 모달창 background와 X 닫기 버튼 분리

## 설명
- `useModal` 훅은 `<Modal />`에서 처음 호출됩니다.
- 훅 호출을 줄이고자 `props`로 전달했습니다.
- 사용하는 곳에서는 `openModal`을 이용해 렌더링 하고 싶은 컴포넌트를 바로 전달할 수 있습니다.
   - 모달 내부 구현과 제어 코드를 관리할 필요가 없습니다.

## 사용 예시
![Snap](https://github.com/f-lab-edu/debus/assets/93242226/65623476-a88a-434f-a4f3-a89945995601)

## 상태 흐름
![modal2](https://github.com/f-lab-edu/debus/assets/93242226/2308c3d6-b3f7-4a16-b123-c7e1dc95943a)

## 관련 이슈
close #10

2024-02-29 11:33 UTC, k-jeonghee commented
```tsx
const Home = () => {
    const { openModal, closeModal } = useModal();

    const confirm = () => {
        const id = uuidv4();
        openModal({
            id,
            element: <ConfirmModal close={() => closeModal(id)} />,
        });
    };

    return (
        <div>
            <button onClick={confirm}>Confirm</button>
        </div>
    );
};
```

모달을 호출하는 곳에서 id를 생성해서 객체로 전달해주어야 해요. `openModal` 함수 내부에서 `id`를 부여하고 싶은데 쉽지 않습니다 ㅠㅠ

2024-02-29 15:00 UTC, f-lab-jake commented
차라리 `openModal`이 `id`를 리턴하는게 낫겠죠?
그리고 저렇게 하면 모달을 임의로 close하고 싶을땐 어떻게 할건가요?

2024-02-29 15:02 UTC, f-lab-jake commented
또 다른 문제도 있습니다. modal container가 unmount되어도 모달 상태는 그대로 남아있겠죠? 
다시 modal container가 mount되어을때 이전에 렌더링 해놓은 모달이 그대로 다시 뜰겁니다.
이게 modal state의 life cycle을 atom을 써서 굳이 뷰랑 분리한 결과입니다

2024-03-09 15:55 UTC, k-jeonghee commented
## 개선사항
기존과 동일하게 `openModal`에 모달 컴포넌트를 직접 받지만 렌더링 되는 방식을 개선했습니다.

1. `ContextProvider`에서 `ModalPortal`로 `<Modal />`컴포넌트를 감싸서 렌더링 합니다.
2. `renderModal`을 이용해 호출 컴포넌트에서 모달 컴포넌트를 바로 반환하면서 뷰는 외부에 나타납니다.
     - 모달 컴포넌트는 호출 컴포넌트의 자식이 됩니다.
3. `Provider`로 Root 컴포넌트를 감싸지 않아도 모달을 호출하고 싶은 컴포넌트에 `Provider`를 감싸는 방식으로 부분 적용합니다.
     - 부분 적용된 컴포넌트가 `unmount` 되면 `Context`도 함께 `unmount` 되어 리렌더링이나 라우팅 변화에 대응할 수 있습니다.

2024-03-10 05:23 UTC, f-lab-jake requested changes

2024-03-10 05:23 UTC, f-lab-jake commented on src/context/ModalContext.tsx
> +export const useModal = () => useContext(modalContext);
현재 `closeModal`을 하면 짝지어진 `openModal`로 연 모달이 닫히는게 아니라 최상단의 모달이 닫힙니다.

2024-03-10 05:23 UTC, f-lab-jake commented on src/components/Modal/ModalPortal.tsx
> +    return createPortal(children, document.getElementById('modal-root')!);
모달 컨테이너를 여러개 쓰고 싶다면 `id`를 각각 다르게 해야합니다.
근데 이건 나중에 해도 괜찮습니다.

2024-03-10 05:23 UTC, f-lab-jake commented on src/components/Modal/Modal.tsx
> +            <ModalContainer onClose={closeModal}>{modal}</ModalContainer>
두 컴포넌트를 그냥 합쳐도 되지 않을까요?

2024-03-10 07:24 UTC, k-jeonghee commented on src/context/ModalContext.tsx
> +export const useModal = () => useContext(modalContext);
지금은 같은 `useModal`훅의 `openModal`을 사용할 경우 1개의 `modals` 배열 안에 쌓은 뒤에 `closeModal`을 하면 마지막 모달부터 순차적으로 닫고 있습니다.

- 모달 컴포넌트를 호출 컴포넌트의 자식으로 바로 반환하면서 `App` 컴포넌트에는 `ModalContextProvider`를 제거했습니다. 
만일 같은 컴포넌트에서 별도 서브뷰를 원할 때는 `Provider`를 한 번 더 감싸서 독립적인 컨텍스트를 갖게 되면 다른 `modals` 상태를 가질 수 있습니다.

짝지어진 `openModal`로 연 모달이 닫히는 것은 `id`를 적용했을 때 가능하지 않을까요?🤔

2024-03-10 07:24 UTC, k-jeonghee commented on src/components/Modal/Modal.tsx
> +            <ModalContainer onClose={closeModal}>{modal}</ModalContainer>
`Overlay`도 커스텀이 필요한 경우가 있을 수도 있고(ex. 투명배경), 다른 레이아웃의 모달이 필요할 수도 있을 것 같아 분리해두었습니다!

2024-03-10 16:58 UTC, k-jeonghee commented
## 개선사항

1. `openModal` 호출 시 내부적으로 `id`를 생성해 `modals` 상태를 저장합니다.
2. `renderModal`로 렌더링되는 `Modal` 컴포넌트는 각각 `id`를 갖습니다.
3. `closeModal`은 모달의 `id`를 이용해 해당하는 모달을 닫습니다.
이를 위해 `Modal` 컴포넌트에서 해당하는 `id` 모달을 닫는 `onCloseModal`을 `props`로 내려줍니다.
4. `ModalContainer`로 모달 컴포넌트를 동적으로 받으면서 `onCloseModal`을 적용하기 위해 `cloneElement`를 이용했습니다.

## 고민했던 부분
`createPortal`과 `Modal`을 1:1 연결 시 모달이 닫혀도 포탈이 `dom`에 남게 되어 `createPortal`은 1개만 적용하면서 모든 모달이 1개의 `modal-root`의 자식으로 렌더링 됩니다. 우선 `ModalContainer`에도 `id`를 부여하긴 했지만 이미 `Modal`에 각각 `id`를 부여해 특정 모달을 닫을 수 있어 모달 컨테이너의 `id`는 큰 역할을 하지 않습니다.

2024-03-11 00:56 UTC, f-lab-jake commented on src/context/ModalContext.tsx
> +export const useModal = () => useContext(modalContext);
`id`가 필요하긴 한데 내부적으로 `id`를 사용하면 됩니다. 사용자한테 보일필요는 없고요.

2024-03-11 01:04 UTC, f-lab-jake requested changes

2024-03-11 01:04 UTC, f-lab-jake commented on src/context/ModalContext.tsx
> +export const useModal = () => useContext(modalContext);
즉 closeModal이 `id`를 인자로 받으면 안됩니다. 지금 문제는 `useModal = () => useContext(modalContext);` 여기에 있습니다. `useModal`이 내부 상태를 가져야 제가 말한대로 구현할수 있습니다.

또한 `renderModal`가 모든 모달을 다 렌더링하지 말고 하나의 바인드된 모달만 렌더링하도록 하세요.

2024-03-11 04:40 UTC, k-jeonghee commented
## 개선사항

1. `ModalContainer`를 `Modal` 컴포넌트로 병합했습니다.
2. `renderModal`이 하나의 모달을 바인드하도록 배열에서 단일 엘리먼트로 수정하여 선택된 모달 상태를 관리하도록 했습니다.
3. `id`는 컨텍스트 내부적으로만 관리하고, `closeModal`은 현재 선택된 모달을 닫습니다.
4. 모달 타입에 `onClose` 이벤트를 막을 수 있는 `showCloseIcon` 옵션을 추가했습니다.

## 질문
현재 컨텍스트 프로바이더를 무조건 `Root`에 두지 않고, 적용할 범위를 좁혀서 필요한 컴포넌트에서 모달을 호출하는 방식으로 동작하고 있습니다. `useModal = () => useContext(modalContext);` 이 부분에는 별도 수정사항이 없는데 제가 피드백을 제대로 이해한 것이 맞을까요?

2024-03-11 11:42 UTC, f-lab-jake requested changes

2024-03-11 11:42 UTC, f-lab-jake commented on src/context/ModalContext.tsx
> +    const openModal = (element: JSX.Element, showCloseIcon: boolean = true) => {
`id`를 밖으로 꺼냅시다.
https://velog.io/@ansrjsdn/useId-hook-%EC%9D%B4%EB%9E%80
얘를 활용해도 좋겠네요

2024-03-11 12:05 UTC, k-jeonghee commented on src/context/ModalContext.tsx
> +    const openModal = (element: JSX.Element, showCloseIcon: boolean = true) => {
컴포넌트 내부 상태에서 관리하는 `id`에 `uuid`가 무겁다고 느꼈는데 변경하니 훨씬 좋습니다.👍

2024-03-12 10:47 UTC, f-lab-jake requested changes

2024-03-12 10:47 UTC, f-lab-jake commented on src/context/ModalContext.tsx
> +    const modalId = useId();
아 이거 제가 코드 전체를 못읽고 리뷰를 드렸네요.
일단 `selectedModal`이 무슨 의미인지 설며해보세요.

그리고 제가 `useModal` 내부에 state 가지라고 한 방법을 다시 고민해보세요. `useId`의 호출은 `useModal`안에 있어야합니다.

2024-03-13 14:01 UTC, k-jeonghee commented
## 개선사항
1. 단일로 변경했던 모달 상태를 배열로 다시 변경했습니다.
2. `ModalContext`는 `modals` 상태와 `open`/`close` 함수로 상태 변경에 대해 관리합니다.
    - `renderModal` 함수를 분리해 모달 상태 관리에만 관심을 갖도록 했습니다.
4. `useModal` 훅에 구현 로직을 작성하고 `hooks` 폴더로 분리했습니다.
    - `modalContext`가 공유하는 데이터를 받아와 재가공하여 상태를 변경하는 함수를 반환합니다.
5. 커스텀훅은 호출 컴포넌트와 독립적으로 동작하여 `cleanup` 처리를 하였습니다.
    - 컴포넌트가 `unmount` 되거나 라우팅 변화가 일어나면 모달도 `unmount` 됩니다.
6. 추가될 `props`를 고려해 미리 모달 `type`을 파일로 분리했습니다.
 
## 결과
1. 훅 호출 시 `modalId`가 함께 바인딩 되어 `openModal`로 열린 모달은 함께 반환된 `closeModal`로만 닫을 수 있습니다. 이때문에 렌더링 되는 `Modal` 컴포넌트는 `closeModal`을 `props`로 받습니다. 추후 비동기 상태 처리 함수가 추가되면 `renderModal`을 통해 `Modal` 컴포넌트의 `props`로 전달할 수 있습니다.
2. `createPortal`을 이용해 뷰는 `root` 외부에 열리지만, 모달 컴포넌트는 호출 컴포넌트의 자식이 됩니다. `ModalProvider`로 최상위 컴포넌트를 감싸두어도 하위 다른 `Provider`의 데이터에 접근할 수 있습니다.

2024-03-14 07:17 UTC, f-lab-jake requested changes

2024-03-14 07:17 UTC, f-lab-jake commented on src/hooks/useModal.tsx
> +        const [modal] = modals.filter((modal) => modal.id === modalId);
`find`씁시다

2024-03-14 07:17 UTC, f-lab-jake commented on src/context/ModalContext.tsx
>      showCloseIcon: boolean;
요런것도 그냥 빼는게 낫습니다. 이걸 라이브러리로 만든다고 생각해보세요. 어차피 누군가 한명은 closeIcon 모양이 마음에 안들어 고치고 싶을것입니다. 그러면 이걸 `false`로 두고 `element`에다가 넣겠죠.

2024-03-14 08:13 UTC, k-jeonghee commented
## 개선사항
1. `renderModal` 함수 내 `filter` 메서드를 `find` 메서드로 변경했습니다.
2. `showCloseIcon`을 제거하고, `Overlay` 컴포넌트에 클릭 방지 옵션을 추가했습니다.
    - 모달 타입에 따라 배경 클릭 시 닫힘을 방지하고 싶을 수 있어 적용했습니다.

2024-03-14 10:52 UTC, f-lab-jake approved these changes

2024-03-14 13:52 UTC, merged