[#14] 모달을 이용한 채팅방 생성 구현 및 TanStack-Query 서버 상태 관리
f-lab-edu/debus pull request #16
Opened 2024-04-04 10:54 UTC by k-jeonghee

## PR 타입
- [X] 기능 추가
- [X] 코드 개선

## 전달사항
- 메시지를 주고 받는 `ChatPanel`은 다음 이슈로 진행하겠습니다.

## 작업 내용
### 최종 모달을 이용한 채팅방 생성 구현

1. `TanStack-Query` 도입 
2. `Section`으로 재사용 가능한 컴포넌트 파일 분리
3. 채팅방 생성 컴포넌트 구현
4. 채팅방 생성 api 작성
   - 이미 존재하는 채팅방 확인 로직 추가
5. `Query Key Factory` 라이브러리를 이용한 `Query Key` 관리
6. 채팅방 생성 후 진입 과정과 관련된 컴포넌트 서버 상태 관리

## 설명
- 채팅방 `Section`을 통해 `방만들기`를 하면 모달이 열립니다. 
- 채팅방이 생성되면 `/lines/:id` 경로로 라우팅 됩니다.
- `LinePage`에서는 채팅방 id를 이용해 상태를 저장합니다.
- `SidePanel`에서는 id를 props으로 받아 데이터를 캐싱하여 하위 컴포넌트로 전달합니다.

## 관련 이슈
close #14

2024-04-05 13:14 UTC, f-lab-jake requested changes

2024-04-05 13:14 UTC, f-lab-jake commented on src/api/firebase.ts
> +    throw new Error('이미 존재하는 정류장 번호입니다.');
요런건 순서를 if조건을 뒤집어서 throw가 먼저 나오는게 좋습니다.

2024-04-05 13:14 UTC, f-lab-jake commented on src/api/firebase.ts
> +export const createChatRoom = async (user: UserTypes | null, chatRoomInfo: ChatRoomInfo) => {
정말 `user`가 `null`일 수 있나요?

2024-04-05 13:14 UTC, f-lab-jake commented on src/components/Section/ChatRooms/ChatRooms.tsx
> +            await createChatRoom(userId, result),
async await 둘다 빼도됩니다. 또는 `createChatRoom`의 타입을 바꾸고 `mutationFn: createChatRoom` 해도 됩니다.

2024-04-05 13:38 UTC, k-jeonghee commented on src/api/firebase.ts
> +export const createChatRoom = async (user: UserTypes | null, chatRoomInfo: ChatRoomInfo) => {
아닙니다! 현재는 로그인 제한 없이 테스트 중이어서 적용했는데 제거 후 대체문자로 처리하였습니다.

2024-04-05 13:38 UTC, k-jeonghee commented on src/components/Section/ChatRooms/ChatRooms.tsx
> +            await createChatRoom(userId, result),
`MutationFunction` 타입을 이용해보았습니다!

2024-04-05 13:53 UTC, f-lab-jake requested changes

2024-04-05 13:53 UTC, f-lab-jake commented on src/components/Section/ChatRooms/ChatRooms.tsx
> +            mutate([user, result]);
튜플로 바꾼 이유가있나요? 튜플이 오브젝트에 비해 실수의 여지가 더 많습니다.

2024-04-05 14:02 UTC, k-jeonghee commented on src/components/Section/ChatRooms/ChatRooms.tsx
> +            mutate([user, result]);
튜플로 했을 때 조금 더 간편해보였습니다..! 다시 오브젝트로 변경했습니다.

2024-04-06 07:40 UTC, f-lab-jake approved these changes

2024-04-06 10:58 UTC, merged