[Feat] Header 컴포넌트 생성 & 다크모드 구현
f-lab-edu/debus pull request #2
Opened 2024-01-16 18:41 UTC by k-jeonghee

## PR 타입
- [X] UI
- [X] 기능 추가

## 작업 내용
1. CSS 초기 설정

2. `RootContainer` 컴포넌트
   - 여백을 유지하면서 Header에 전체 background color 적용을 위한 레이아웃 분리
   - `Page` 컴포넌트에 CSS module 파일을 생성하지 않고 UI 컴포넌트로 작성

3. `Header` 컴포넌트
   - 다크모드 전환 토글 버튼

4. 다크모드 구현
   - ContextAPI
   - Custom Hook
   - 모드 전환에 따라 CSS 클래스 변경 & 테마 정보 저장

## 스크린샷
<img width="1438" alt="feat_2(1)" src="https://github.com/f-lab-edu/debus/assets/93242226/69ea145c-60d9-47d5-8eb9-e95781e84900">
<img width="1438" alt="feat_2" src="https://github.com/f-lab-edu/debus/assets/93242226/f8f2ab0b-acee-48c1-9d34-df918bda7d72">

2024-01-19 02:47 UTC, f-lab-jake requested changes

2024-01-19 02:47 UTC, f-lab-jake commented on src/context/DarkModeContext.tsx
> +    }, []);
훅으로 뺍시다

2024-01-19 06:38 UTC, k-jeonghee commented
`useTheme.ts`로 `useState`와 `toggleDarkMode`를 분리했습니다.
- Hooks 폴더 생성 및 절대경로 설정
- 처음 마운트 되었을 때, 로컬의 테마 정보에 따라 설정이 바뀌어야 해서 옵셔널 파라미터 적용
- `useTheme.ts`에서 return type을 지정하고 context에서 재사용

2024-01-20 02:43 UTC, f-lab-jake requested changes

2024-01-20 02:43 UTC, f-lab-jake commented on src/context/DarkModeContext.tsx
> +    }, [toggleDarkMode]);
훅으로 뺄때 이 로직은 왜 냅두고 가나요?

2024-01-20 03:05 UTC, k-jeonghee commented on src/context/DarkModeContext.tsx
> +    }, [toggleDarkMode]);
훅으로 챙겨왔습니다!

2024-01-20 03:14 UTC, f-lab-jake approved these changes
jotai를 한번 공부해보세요

2024-01-20 04:28 UTC, merged