[#3] ContextAPI에서 Jotai로 변경 후 다크모드 적용
f-lab-edu/debus pull request #4
Opened 2024-01-20 16:52 UTC by k-jeonghee

## PR 타입
- [X] 패키지 추가
- [X] 코드 개선

## 작업 내용
1. Context 폴더 삭제 및 관련 코드 제거
2. Jotai atom으로 다크모드 구현

2024-01-21 12:09 UTC, f-lab-jake requested changes

2024-01-21 12:09 UTC, f-lab-jake commented on src/hooks/useTheme.ts
> +export const useTheme = (): DarkModeState => {
훅을 굳이 안만드려고 jotai를 씁니다.

2024-01-21 12:09 UTC, f-lab-jake commented on src/hooks/useTheme.ts
> +export const useTheme = (): DarkModeState => {
https://velog.io/@taez224/Jotai-Tutorial-Write-Only-atom

2024-01-21 16:47 UTC, k-jeonghee commented
기존 커스텀훅을 제거하고 atom으로 다시 설정했습니다.
1. 상태를 set할 때, 로컬 테마 정보와 css 클래스를 변경하는 함수를 함께 호출합니다.
2. 렌더링 시 테마 상태를 유지하는 코드는 App 컴포넌트에서 구현합니다.

2024-01-22 08:23 UTC, f-lab-jake requested changes

2024-01-22 08:23 UTC, f-lab-jake commented on src/App.tsx
> +    }, [setDarkMode]);
여전히 분리하지 못했습니다.
[`atomWithStorage`](https://jotai.org/docs/utilities/storage)를 참고하세요.

2024-01-22 08:23 UTC, f-lab-jake commented on src/store/atoms/theme.ts
> +    }
렌더링 로직이죠 이건?

2024-01-23 12:38 UTC, k-jeonghee commented
1. Base atom을 `atomWithStorage`로 변경했습니다.
2. 테마 토글 버튼을 컴포넌트로 만들고 내부에서 useEffect를 사용했습니다.
-class를 변경하는 함수는 컴포넌트 밖으로 빼내었습니다.

2024-01-24 08:01 UTC, f-lab-jake requested changes

2024-01-24 08:01 UTC, f-lab-jake commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    }
렌더링 로직을 react 바깥에 넣는걸 피하세요

2024-01-24 13:20 UTC, k-jeonghee commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    }
넵! 변경했습니다.

2024-01-25 04:11 UTC, f-lab-jake requested changes

2024-01-25 04:11 UTC, f-lab-jake commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    };
`document` 직접 dom api로 조작하지 말란 이야기입니다.

2024-01-25 04:11 UTC, f-lab-jake commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    };
지금은 위치만 바뀌었어요.

2024-01-27 13:28 UTC, k-jeonghee commented
멘토님, 기존 Root 페이지를 제거하고 관련 코드를 App 컴포넌트에 작성했습니다. 
- App 컴포넌트
   - 최상위 태그에 다크모드 data-theme 적용
   - 기존 RootContainer 스타일 적용(index.css)

2024-01-29 11:15 UTC, f-lab-jake requested changes

2024-01-29 11:15 UTC, f-lab-jake commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    };
이런 함수는 의미가 없습니다. 이름으로 뭘 알려주는 것도 아니죠. 그냥 props에 인라인으로 쓰는게 낫습니다.

2024-01-29 11:15 UTC, f-lab-jake commented on src/store/atoms/theme.ts
> +);
이거 쓸필요 없이 그냥 `darkModeAtom`을 그대로 쓰면 됩니다. 보시면 얘는 하는게 없어요.

2024-01-29 11:15 UTC, f-lab-jake commented on src/store/atoms/theme.ts
> +);
변수명은 일관성있게 camel case를 써주세요. 다만 atom같은 좀 특이한 그룹에 대해서 다른 룰을 적용하는 것도 의미가 있긴합니다.

2024-01-29 11:15 UTC, f-lab-jake commented on src/App.tsx
> +        <div id="app" data-theme={darkMode ? 'dark' : 'light'}>
넵 이런식으로 하는게 맞습니다. 그리고 그냥 class로 주는게 어떤가요?  data- 로 해놓으면 selector 쓸때 좀 귀찮을수도 있어요. 혹시 참고한 예시가 있다면  공유해주세요.

2024-01-29 11:15 UTC, f-lab-jake commented on src/store/atoms/theme.ts
> +);
`darkMode_atom`을 굳이 추가할거면, write에 toggle 동작을 넣는걸 고려해볼만합니다.

2024-01-29 13:18 UTC, k-jeonghee commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    };
넵, 인라인으로 작성했습니다.

2024-01-29 13:18 UTC, k-jeonghee commented on src/store/atoms/theme.ts
> +);
- 처음엔 atom이 여러 개가 만들어져서 구분이 잘 되지 않아 다른 네이밍 규칙을 적용했는데 개선하면서 큰 의미가 없어졌습니다. 일관성 있게 작성하겠습니다.
- write에 toggle을 적용하니 사용 시 set함수에 인자를 넣지 않아도 되어서 말씀해주신 방법을 적용해보았습니다.

2024-01-29 13:19 UTC, k-jeonghee commented on src/App.tsx
> +        <div id="app" data-theme={darkMode ? 'dark' : 'light'}>
이전에는 html 또는 body에 직접 테마 상태를 지정하는 참고 자료를 보고 dataset을 고려했어요.
(참고 링크: https://lukelowrey.com/css-variable-theme-switcher/)
- App 컴포넌트는 module.css를 만들지 않고, index.css에서 id 선택자를 이용하고 있어서 목적이 구분되면 좋을 것 같아 dataset을 적용했었습니다.

2024-01-29 14:34 UTC, f-lab-jake approved these changes

2024-01-29 14:34 UTC, f-lab-jake commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    const [darkMode, setDarkMode] = useAtom(darkModeAtom);
이렇게할때는 이름을 `toggleDarkMode`로 하는게 낫겠죠

2024-01-29 14:47 UTC, k-jeonghee commented on src/components/UI/ThemeButton/ThemeButton.tsx
> +    const [darkMode, setDarkMode] = useAtom(darkModeAtom);
넵! 네이밍 다시 한 번 체크하겠습니다. 변경 후 머지하겠습니다!

2024-01-29 14:59 UTC, merged