[#5] Firebase 인증 로직 구현 및 Header 컴포넌트 상태 변경 적용
f-lab-edu/debus pull request #6
Opened 2024-02-01 13:49 UTC by k-jeonghee

## PR 타입
- [X] 기능 개발
- [X] 패키지 추가

## 작업 내용
1. Firebase 인증 설정 및 api 작성
   - login, logout, onAuthStateChanged(상태 변경 감지)
   - `.env` 파일 생성 후 key 관리
3. Auth atom으로 user 정보 전역 관리
4. 로그인 유무에 따라 Header 변경
5. 로그인 사용자 프로필 이미지
   - svg 파일 컴포넌트화 설정
   - 이미지 컬러 고정값 -> 랜덤 컬러 적용 예정

## 스크린샷
<img width="1430" alt="프로필이미지" src="https://github.com/f-lab-edu/debus/assets/93242226/f35f0611-9448-413a-a5af-c14880f16645">

## 관련 이슈
close #5

2024-02-03 03:40 UTC, k-jeonghee commented
- Header에 작성했던 useEffect를 제거하고 atom에 onMount를 적용했습니다.
- atom을 캡슐화하여 외부 컴포넌트에서는 atom을 쓰지 않고 반환된 결과만 사용할 수 있도록 해보았습니다.

2024-02-13 16:02 UTC, k-jeonghee commented
## 작업내용
onMount 코드를 개선하면서 기능을 추가했습니다.
1. onMount - return으로 언마운트 시 옵저버 구독 해제
2. 전역으로 저장하는 사용자 정보 간소화
3. 데이터베이스 사용자 저장 로직 구현
   - 로그인 시 데이터베이스 확인 후 없으면 생성

2024-02-14 15:18 UTC, f-lab-jake requested changes

2024-02-14 15:18 UTC, f-lab-jake commented on src/api/firebase.ts
> +        });
의도가 뭔가요?

2024-02-14 15:18 UTC, f-lab-jake commented on src/api/firebase.ts
>  export const login = async () => {
async 빼도됩니다. 왜일까요?

2024-02-14 15:18 UTC, f-lab-jake commented on src/api/firebase.ts
> +                    throw new Error(error);
의도가 뭔가요?

2024-02-14 15:18 UTC, f-lab-jake commented on src/api/firebase.ts
> +    });
요부분 잘 이해가안되는데 firebase api를 좀더 살펴보고 다시 리뷰할게요

2024-02-14 15:18 UTC, f-lab-jake commented on src/store/atoms/auth.ts
> +    return () => unsubscribe();
그냥 `return unsubscribe`해도 되겠죠?
또 `onUserStateChange`를 바로 return해도 되고요

2024-02-14 15:18 UTC, f-lab-jake commented on src/store/atoms/auth.ts
>  export const useAuth = () => useAtomValue(authAtom);
이런거 따로 안만들어도 됩니다.

2024-02-14 16:29 UTC, kjheee commented on src/store/atoms/auth.ts
> +    return () => unsubscribe();
넵! `unsubscribe` 강조해보려고 했는데 바로 return 하니 깔끔한 것 같습니다!

2024-02-14 16:29 UTC, kjheee commented on src/store/atoms/auth.ts
>  export const useAuth = () => useAtomValue(authAtom);
이렇게 캡슐화를 하면 컴포넌트에서 atom의 정보를 알 필요 없고 `useAuth` 1개만 import 할 수 있어 적용해보았는데 크게 의미 없을까요~?

2024-02-14 16:29 UTC, kjheee commented on src/api/firebase.ts
> +    });
넵, 요부분에 대해 간단히 추가 설명을 드리면
- 체크해주신 라인의 코드는 파이어베이스 Realtime Database에 uid를 경로로 2번째 인자인 객체 정보를 저장합니다.
- `onAuthStateChanged`에서 data 객체를 만든 이유는 기본으로 받아오는 User 정보가 많아 그 중에서 필요한 정보만 추려서 저장하기 위함입니다.
- `checkUserExists`와 `createUser`는 소셜 로그인 성공 후 데이터베이스에 사용자가 있는지 확인하여 없으면 저장하는 로직을 추가하고자 따로 작성했습니다.

2024-02-14 16:29 UTC, kjheee commented on src/api/firebase.ts
> +                    throw new Error(error);
이 부분은 `createUser` 비동기 함수의 에러 처리를 위해 적용하고, 위 `signInWithPopup`를 위해 적용해보았는데 사용 방법이 잘못되었을까요~?

2024-02-14 16:29 UTC, k-jeonghee commented on src/api/firebase.ts
>  export const login = async () => {
login 함수에서 직접 비동기 처리 코드를 작성하지 않고, 내부에서 호출되는 `signInWithPopup`를 통해 실행하므로 login 자체에는 async를 붙일 필요가 없습니다. 처음에 `signInWithPopup`를 return하여 컴포넌트에서 핸들링 하는 코드를 작성했다가 개선하면서 이 부분을 놓쳤습니다...!

2024-02-15 09:16 UTC, f-lab-jake commented on src/api/firebase.ts
>  export const login = async () => {
맞습니다. 더 정확하게 표현하면 await을 안 써서 그렇습니다.

2024-02-15 09:17 UTC, f-lab-jake commented on src/api/firebase.ts
> +                    throw new Error(error);
`. catch(...)` 구문을 빼도 됩니다. 저런 식으로 동작을 이해하지 못한채로 쓰는 코드를
https://en.wikipedia.org/wiki/Cargo_cult_programming
라고 합니다.

2024-02-15 09:18 UTC, f-lab-jake commented on src/store/atoms/auth.ts
>  export const useAuth = () => useAtomValue(authAtom);
네네. 저런 간단한 코드를 감싸서 좋은 경우는, 나중에 그 동작을 실행하려는 코드를 검색하기가 쉬워지는 경우입니다. 그런데 이경우엔 어차피 `authAtom`으로 검색하면 똑같은 코드들을 볼수있습니다

2024-02-15 09:19 UTC, f-lab-jake commented on src/store/atoms/auth.ts
>  export const useAuth = () => useAtomValue(authAtom);
앞으로 이런식으로 atom추가할때마다 일관성있게 훅을 추가하는건 또 귀찮을거같죠?

2024-02-15 09:59 UTC, k-jeonghee commented on src/api/firebase.ts
> +                    throw new Error(error);
아하 혹시 catch 구문을 빼도 되는 이유가 유의미한 에러 처리를 하고 있지 않아서일까요? 아니면 catch를 쓰는 패턴이 따로 있을까요~?

2024-02-15 09:59 UTC, k-jeonghee commented on src/store/atoms/auth.ts
>  export const useAuth = () => useAtomValue(authAtom);
넵, 코드 검색으로 생각해보니 필요한 상황이 쉽게 이해가 되네요! 다음부터 참고하여 작성하도록 하겠습니다!

2024-02-15 11:17 UTC, f-lab-jake commented on src/api/firebase.ts
> +                    throw new Error(error);
그래서 원래 쓴 코드의 의도를 물은겁니다.
사실 거의 아무 것도 안하는(빼는거랑 완전 똑같은 동작은 아닙니다) 코드라서,
어떻게 동작하길 기대하고 썼는지가 궁금합니다

2024-02-15 11:46 UTC, k-jeonghee commented on src/api/firebase.ts
> +                    throw new Error(error);
제가 질문을 잘못 이해하고 답변했습니다. 요번 코드에서는 디버깅의 용도지만 `signInWithPopup`의 경우에는 추후 클라이언트에서 로그인 실패를 안내할 수 있도록 처리하고 싶습니다!

2024-02-15 12:47 UTC, f-lab-jake commented on src/api/firebase.ts
> +                    throw new Error(error);
디버깅의 용도로는 어떤걸 의도한건가요?

2024-02-15 12:58 UTC, k-jeonghee commented on src/api/firebase.ts
> +                    throw new Error(error);
에러가 어디에서 발생했는지 확인하기 위함이었는데 다시보니 그것만으로는 의미가 없는 코드인 것 같아요. 에러를 어떻게 처리할지도 정해져 있지 않고, 메시지도 별다른 구분이 없어 오히려 디버깅이 어려울 수도 있겠다는 생각도 듭니다...!

2024-02-20 08:05 UTC, k-jeonghee commented
## 작업내용 
- 단일 atom 캡슐화 제거
- 함수 포맷팅 정리
- 에러 핸들링 코드 제거
      - 추후 클라이언트에서 처리할 수 있도록 개선

2024-02-20 11:31 UTC, f-lab-jake requested changes

2024-02-20 11:31 UTC, f-lab-jake commented on src/api/firebase.ts
> +        photoURL: user?.photoURL,
실제로 `null`이 들어가면 안되는 값들이죠?

2024-02-20 11:43 UTC, k-jeonghee commented on src/api/firebase.ts
> +        photoURL: user?.photoURL,
넵, assert 함수가 있어 옵셔널을 제거해도 에러가 나지 않아 제거하는 것으로 수정했습니다!

2024-02-21 08:10 UTC, k-jeonghee commented
객체 내에서 user의 정보를 사용하고 있어 null 병합 연산자 적용 시 에러가 발생하여 삼항연산자로 개선하였습니다.

2024-02-24 10:03 UTC, f-lab-jake approved these changes

2024-02-24 10:03 UTC, f-lab-jake commented on src/api/firebase.ts
> +            user
`user &&`이 낫겟죠?

2024-02-25 00:51 UTC, merged

2024-02-26 11:09 UTC, f-lab-jake commented on src/store/atoms/auth.ts
> +authAtom.onMount = (set) => onUserStateChange(set);
요런거 그냥 `= onUserStateChange` 해도됩니다